### ISSUE TITLE
Stock gulp-less throws error

### ISSUE THREAD

**Issue by zrpnr** [AtenDesignGroup/stylizer-front-end#12]
Fresh clone of repo, `npm-install` then `gulp` throws error:

```
stylizer-front-end/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function
```

May be an issue with the version of gulp-less in package.json, running `npm install gulp-less` seems to solve.

**Comment by pixelwhip** [comment]
Replaced less with sass.
